version: "3.7"
services:
  app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    expose:
      - 3000
  test:
    build:
      context: .
      target: test
      dockerfile: Dockerfile